version: 2
jobs:
  build:
    docker:
      - image: rocker/r-ver:3.5.3
    steps:
      - checkout
      
      - run:
          name: Convert packages.txt to unix line-endings
          command: apt-get update && apt-get install -y dos2unix && dos2unix packages.txt
      
      - restore_cache:
         keys:
           - sys-deps-v1-{{ checksum "packages.txt" }}
           - sys-deps-v1
           - r-deps-v1-{{ checksum "DESCRIPTION" }}
           - r-deps-v1
           
      - run:
          name: Install system dependencies
          command: apt-get update && cat packages.txt | xargs apt-get install -y
          
      - save_cache:
          key: sys-deps-v1-{{ checksum "packages.txt" }}
          paths:
            - /usr/bin
          
      - run:
          name: Install devtools
          command: R -e "install.packages('devtools', repos='http://cran.us.r-project.org')"
          
      - save_cache:
          key: r-deps-v1-{{ checksum "DESCRIPTION" }}
          paths:
            - /usr/local/lib/R/site-library
          
      - run:
          name: Install package dependencies
          command: R -e "devtools::install_deps(dep = TRUE, repos='http://cran.us.r-project.org')"
      
      - run:
          name: Build package
          command: R CMD build .
      
      - run:
          name: Check package
          command: R CMD check *tar.gz
          
      - run:
          name: Testing using testthat
          command: R -e "devtools::test()"
          
      - store_artifacts:
          path: /root/project/rdbcnxn.Rcheck/
  
#     working_directory: ~/main
#     docker:
#       - image: appsilon/ci-base:1.0
#     steps:
#       - checkout
#       - restore_cache:
#           keys:
#             - deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
#             - deps1-{{ .Branch }}
#             - deps1-
#       - run:
#           command: |
#             R -e 'devtools::install_deps(dependencies = TRUE)'
#       - save_cache:
#       
#       
#       
#           key: deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
#           paths:
#             - "/usr/local/lib/R/site-library"
#       - run:
#           command: |
#             R -e 'devtools::check()'
#       - store_artifacts:
#           path: man/
#           destination: man